In [1]:
import numpy as np
import scipy as sp
from scipy import optimize
#from scipy.signal import find_peaks
import matplotlib.ticker as ticker
from scipy import interpolate
import os
import matplotlib.pyplot as plt
%config InlineBackend.figure_format = 'retina'

In [2]:
filenames = os.listdir('/Users/ksenia/Desktop/lupyr_Kornilov/Pyro/')
filenames

['1706_down.txt',
 'Видеозахват экрана_Тантал 800бар.avi',
 '2201_up.txt',
 '2599_up.txt',
 'execute.ipynb',
 '1396_up.txt',
 '2105_down.txt',
 '1903_down.txt',
 '.DS_Store',
 '2405_down.txt',
 '2798_up.txt',
 'Untitled.ipynb',
 'Ca_exp1.txt',
 '2700_up.txt',
 'Ti_exp4.txt',
 'Ca_test.txt',
 'Ca_exp2.txt',
 'Ca_exp3.txt',
 'Ti_exp5.txt',
 'Ti_exp1.txt',
 '2605_down.txt',
 '2899_up.txt',
 '1699_up.txt',
 'Ti_exp2.txt',
 'Ca_exp4.txt',
 'Ti_exp3.txt',
 '2498_up.txt',
 '2504_down.txt',
 '1502_down.txt',
 '2805_down.txt',
 '1897_up.txt',
 '1997_up.txt',
 '1501_up.txt',
 'Al_exp3.txt',
 'Al_exp2.txt',
 '1309_up.txt',
 'Al_exp1.txt',
 '2004_down.txt',
 '.ipynb_checkpoints',
 '2705_down.txt',
 '1601_down.txt',
 'Zn_exp2.txt',
 'Zn_exp1.txt',
 '1804_down.txt',
 '2307_down.txt',
 '2298_up.txt',
 '1597_up.txt',
 '2097_up.txt',
 '2204_down.txt',
 'calibration.png',
 '1798_up.txt',
 '2400_up.txt']

In [3]:
np.sort(filenames)

array(['.DS_Store', '.ipynb_checkpoints', '1309_up.txt', '1396_up.txt',
       '1501_up.txt', '1502_down.txt', '1597_up.txt', '1601_down.txt',
       '1699_up.txt', '1706_down.txt', '1798_up.txt', '1804_down.txt',
       '1897_up.txt', '1903_down.txt', '1997_up.txt', '2004_down.txt',
       '2097_up.txt', '2105_down.txt', '2201_up.txt', '2204_down.txt',
       '2298_up.txt', '2307_down.txt', '2400_up.txt', '2405_down.txt',
       '2498_up.txt', '2504_down.txt', '2599_up.txt', '2605_down.txt',
       '2700_up.txt', '2705_down.txt', '2798_up.txt', '2805_down.txt',
       '2899_up.txt', 'Al_exp1.txt', 'Al_exp2.txt', 'Al_exp3.txt',
       'Ca_exp1.txt', 'Ca_exp2.txt', 'Ca_exp3.txt', 'Ca_exp4.txt',
       'Ca_test.txt', 'Ti_exp1.txt', 'Ti_exp2.txt', 'Ti_exp3.txt',
       'Ti_exp4.txt', 'Ti_exp5.txt', 'Untitled.ipynb', 'Zn_exp1.txt',
       'Zn_exp2.txt', 'calibration.png', 'execute.ipynb',
       'Видеозахват экрана_Тантал 800бар.avi'], 
      dtype='<U36')

# Чтение файлов

In [4]:
def read_file(directory, file_name, flag):
    f = open(directory+file_name, 'r')
    line = f.readline()
    time = []
    spc = []
    while line:
        t, s = map(float, line.replace(',', '.').split())
        time.append(t)
        spc.append(s)
        line = f.readline()
    f.close()
    spc = np.array(spc)
    time = np.array(time)
    if flag:
        return time, spc
    else:
        return spc

In [5]:
directory = "/Users/ksenia/Desktop/lupyr_Kornilov/Pyro/"
up = []
down = []
I_up = []
I_down = []
for name in np.sort(filenames):
    if name[-6:-4]=='up':
        spc = []
        spc = read_file(directory, name, False)
        up.append(spc)
        I_up.append(int(name[:4]))
    elif name[-6:-4]=='wn':
        spc = []
        spc = read_file(directory, name, False)
        down.append(spc)
        I_down.append(int(name[:4]))
I_up = np.array(I_up[:-2])/100
I_down = np.array(I_down[:-1])/100

In [6]:
I_calib = [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
T_calib = [1547, 1631, 1707, 1776, 1841, 1904, 1964, 2022, 2078, 2133, 2186, 2239, 2290, 2341, 2389, 2437, 2484]
f = interpolate.interp1d(I_calib, T_calib)

In [7]:
I_up

array([ 13.09,  13.96,  15.01,  15.97,  16.99,  17.98,  18.97,  19.97,
        20.97,  22.01,  22.98,  24.  ,  24.98,  25.99,  27.  ])

In [8]:
T_up = f(I_up)
T_down = f(I_down)

In [9]:
T_up

array([ 1554.56,  1627.64,  1707.69,  1773.93,  1840.35,  1902.74,
        1962.2 ,  2020.26,  2076.32,  2133.53,  2184.94,  2239.  ,
        2288.98,  2340.49,  2389.  ])

In [10]:
T_down

array([ 1708.38,  1776.65,  1844.78,  1906.4 ,  1965.74,  2024.24,
        2080.75,  2135.12,  2189.71,  2241.55,  2292.04,  2343.4 ,  2391.4 ])

In [11]:
f(np.array([13.45, 14]))

array([ 1584.8,  1631. ])

In [12]:
U_up = []
U_down = []
for arr in up[:-2]:
    U_up.append(np.mean(arr))
for arr in down[:-1]:
    U_down.append(np.mean(arr))

In [26]:
print(U_down)

[0.21101785999999997, 0.29452672750000003, 0.37232276250000002, 0.43760827249999995, 0.50008947000000004, 0.55883690750000004, 0.61305218750000001, 0.6642711724999999, 0.713872065, 0.75894593499999996, 0.79982936000000004, 0.83363215000000002, 0.86186095500000015]


In [13]:
def lin(x, a, b):
    return a + b / x

In [14]:
a_up, b_up = optimize.curve_fit(lin, T_up, U_up)[0]
a_down, b_down = optimize.curve_fit(lin, T_down, U_down)[0]

In [29]:
print(list(a_down + b_down/T_down))

[0.20271034253814602, 0.29176010707721955, 0.37405656785233754, 0.44342347232655133, 0.50611324124115775, 0.56431780250082153, 0.61743469173475196, 0.66588609640806662, 0.7121128542940991, 0.75392661137023165, 0.79283327397424697, 0.83069022456717745, 0.86460053911213941]


In [15]:
sp.optimize.curve_fit(lin, T_up, U_up)

(array([  2.31872582e+00,  -3.61516091e+03]),
 array([[  8.72847359e-05,  -1.68874752e-01],
        [ -1.68874752e-01,   3.32523610e+02]]))

In [16]:
sp.optimize.curve_fit(lin, T_down, U_down)

(array([  2.52013035e+00,  -3.95903400e+03]),
 array([[  1.88757328e-04,  -3.82178779e-01],
        [ -3.82178779e-01,   7.82352168e+02]]))

In [17]:
import matplotlib
matplotlib.rc('font', family='Verdana')

plt.figure(figsize=(5, 10))

plt.plot(1/T_up, U_up, 'bo', color='b', label='Повышение температуры' )
x_min, x_max = np.min(1/T_up), np.max(1/T_up)
x = np.linspace(x_min, x_max, 10)
plt.plot(x, a_up + b_up * x)

plt.plot(1/T_down, U_down, 'bo', color='g', label='Понижение температуры')
x_min, x_max = np.min(1/T_down), np.max(1/T_down) 
x = np.linspace(x_min, x_max, 10)
plt.plot(x, a_down + b_down * x)

plt.legend(numpoints = 1)
plt.xlabel("$ \\frac{1}{T}, \\frac{1}{K} $", fontsize='xx-large');
plt.ylabel("U, B", fontsize='xx-large');
#plt.text(4, 9, "U = (2.319 \pm 0.001) - (3615 \pm 18) frac{1}{T}", {'color': 'b', 'fontsize': 18})
#plt.show()

In [18]:
C1, C2 = 3.7413*10**(-16), 1.4380*10**(-2)

In [19]:
-0.375 * C2/np.log(10) / b_up

6.4780878407607241e-07

In [22]:
6.4780878407607241*0.03/3.96

0.04907642303606609

In [20]:
-0.375 * C2/np.log(10) / b_down

5.9154152107741111e-07

In [23]:
5.9154152107741111*0.03/3.96

0.04481375159677357

In [ ]:
ca = []
al = []
ti = []
zn = []
for name in filenames:
    if name[:2]=='Ca':
        spc = []
        time = []
        time, spc = read_file(directory, name, True)
        ca.append([time, spc])
    elif name[:2]=='Al':
        spc = []
        time = []
        time, spc = read_file(directory, name, True)
        al.append([time, spc])
    elif name[:2]=='Ti':
        spc = []
        time = []
        time, spc = read_file(directory, name, True)
        ti.append([time, spc])
    elif name[:2]=='Zn':
        spc = []
        time = []
        time, spc = read_file(directory, name, True)
        zn.append([time, spc])

In [ ]:
def U2T(a, b, u):
    return b / (u - a)

In [ ]:
for arr in ca:
    arr[1] = U2T(a_up, b_up, arr[1])
for arr in al:
    arr[1] = U2T(a_up, b_up, arr[1])
for arr in ti:
    arr[1] = U2T(a_up, b_up, arr[1])
for arr in zn:
    arr[1] = U2T(a_up, b_up, arr[1])

In [ ]:
for arr in ca:
    plt.figure(figsize=(10, 10))
    plt.plot(arr[0], arr[1])
    plt.xlabel('t, sec', fontsize='xx-large')
    plt.ylabel('T, K', fontsize='xx-large')
    plt.title('Ca', fontsize='xx-large')
    
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')
    ax = plt.axes()
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(0.2))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(500))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(100))
    plt.grid(True, which='major', linewidth = 1.7, color = 'grey')
    plt.grid(True, which='minor', linewidth = 0.5)
    plt.show()

In [ ]:
for arr in al:
    plt.figure(figsize=(10, 10))
    plt.plot(arr[0], arr[1])
    plt.xlabel('t, sec', fontsize='xx-large')
    plt.ylabel('T, K', fontsize='xx-large')
    plt.title('Al', fontsize='xx-large')
    
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')
    ax = plt.axes()
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(0.2))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(500))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(100))
    plt.grid(True, which='major', linewidth = 1.7, color = 'grey')
    plt.grid(True, which='minor', linewidth = 0.5)

In [ ]:
for arr in ti:
    plt.figure(figsize=(10, 10))
    plt.plot(arr[0], arr[1])
    plt.xlabel('t, sec', fontsize='xx-large')
    plt.ylabel('T, K', fontsize='xx-large')
    plt.title('Ti', fontsize='xx-large')
    
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')
    ax = plt.axes()
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(0.2))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(500))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(100))
    plt.grid(True, which='major', linewidth = 1.7, color = 'grey')
    plt.grid(True, which='minor', linewidth = 0.5)

In [ ]:
for arr in zn:
    plt.figure(figsize=(10, 10))
    plt.plot(arr[0], arr[1])
    plt.xlabel('t, sec', fontsize='xx-large')
    plt.ylabel('T, K', fontsize='xx-large')
    plt.title('Zn', fontsize='xx-large')
    
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')
    ax = plt.axes()
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1))
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(0.2))
    ax.yaxis.set_major_locator(ticker.MultipleLocator(500))
    ax.yaxis.set_minor_locator(ticker.MultipleLocator(100))
    plt.grid(True, which='major', linewidth = 1.7, color = 'grey')
    plt.grid(True, which='minor', linewidth = 0.5)

In [ ]:
def read_file2(file_name):
    f = open(file_name, 'r')
    line = f.readline()
    time = []
    spc = []
    while line:
        t, s = map(float, line.replace(',', '.').split())
        time.append(t)
        spc.append(s)
        line = f.readline()
    f.close()
    spc = np.array(spc)
    time = np.array(time)
    return(time, spc)

In [ ]:
spc1 = read_file2('/Users/ksenia/Desktop/lupyr_Kornilov/Pyro/1309_up.txt')

In [ ]:
import matplotlib
matplotlib.rc('font', family='Verdana')

plt.figure(figsize=(10, 10))
plt.plot(spc1[0], spc1[1])
plt.xlabel('t, c', fontsize='xx-large')
plt.ylabel('U, B', fontsize='xx-large')
plt.show()

- Написать введение
- Ошибки 
- температуры плавления
- ошибка 650 - 648
- приближение Вина